apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-client
spec:
  template:
    spec:
      initContainers:
        - name: sfunnel-init
          image: sfunnel
        - name: sfunnel-init-egress
          image: sfunnel
