apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../test/cni

patches:
  - path: example-patch-negative.yaml
    target:
      kind: Deployment
      name: my-nginx-deployment
