apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nginx-app
  template:
    metadata:
      labels:
        app: my-nginx-app
    spec:
      initContainers:
        - name: sfunnel-init
          image: ghcr.io/datahangar/sfunnel:0.0.8@sha256:53c6ad27e82903b853876b5dbcc6f612f0d94ec61f78ec4759865f5e2b50de12
          env:
            - name: SFUNNEL_RULESET
              value: ip tcp dport 80 sport 540 actions unfunnel tcp
          securityContext:
            privileged: false
            capabilities:
               add: [BPF, NET_ADMIN, SYS_ADMIN]
          volumeMounts:
            - name: bpffs
              mountPath: /sys/fs/bpf
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
      volumes:
        - name: bpffs
          hostPath:
            path: /sys/fs/bpf
