apiVersion: v1
kind: Service
metadata:
  name: my-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: my-nginx-app
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80
    - name: web-alt
      protocol: TCP
      port: 8080
      targetPort: 8080
  sessionAffinity: ClientIP
  internalTrafficPolicy: Local #Do not SNAT to the service!
---
apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: my-nginx-app
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80
    - name: web-alt
      protocol: TCP
      port: 8080
      targetPort: 8080
  sessionAffinity: ClientIP
  externalTrafficPolicy: Local #Do not SNAT to the service!
