name: ci

on:
  push:
  pull_request:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  make_check:
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout sfunnel"
        uses: actions/checkout@v4
        with:
          path: sfunnel
          fetch-depth: 0
          fetch-tags: 1

      - name: "Install deps..."
        run: |
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y clang make iproute2 bridge-utils python3 \
                                  python3-scapy python3-pip libbpf-dev \
                                  libelf-dev linux-headers-generic \
                                  linux-libc-dev llvm iptables
          sudo pip3 install pytest
          sudo ln -s /usr/include/x86_64-linux-gnu/asm /usr/include/asm

      - name: "Allow test traffic in iptables/nftables"
        run: |
          sudo iptables -L -n
          sudo iptables -t nat -L -n
          sudo iptables -I FORWARD -s 11.1.1.1 -j ACCEPT

      - name: "Run tests..."
        run: cd sfunnel/test && make
